name=MicroModbus
version=0.0.1
author=Oscar Davidson
maintainer=Oscar Davidson <heavybaremetal@gmail.com>
sentence=Cross-platform C++ Modbus library, very low RAM/ROM use
paragraph=Designed to be reliable and easy to use, with many message handlers already written
category=Communication
url=https://github.com/OscarDavidson/MicroModbus
architectures=*
license=MIT